backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
collections:
  - name: home
    label: Home
    folder: 'content/pages'
    create: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Subtitle'
        name: 'subtitle'
        widget: 'string'
      - label: 'Background Image'
        name: 'backgroundImage'
        widget: 'image'
  - name: bio
    label: Bio
    folder: public/content/pages
    create: true
    fields:
      - label: 'Bio Image'
        name: 'bio_image'
        widget: 'image'
  - name: teaching
    label: Teaching
    folder: public/content/pages
    create: true
    fields:
      - label: 'Teaching Philosophy'
        name: 'teaching_philosophy'
        widget: 'markdown'
      - label: 'Studio Policy'
        name: 'studio_policy'
        widget: 'markdown'
      - label: 'tp-image'
        name: 'tp_image'
        widget: 'image'
      - label: 'sp-image'
        name: 'sp_image'
        widget: 'image'
      - label: 'contact-image'
        name: 'contact_image'
        widget: 'image'
  - name: samples
    label: Sample Videos
    folder: public/content/pages
    create: true
    fields:
      - label: 'YouTube ID #1'
        name: 'id_1'
        widget: 'string'
      - label: 'YouTube ID #2'
        name: 'id_2'
        widget: 'string'
      - label: 'YouTube ID #3'
        name: 'id_3'
        widget: 'string'
      - label: 'YouTube ID #4'
        name: 'id_4'
        widget: 'string'
      - label: 'YouTube ID #5'
        name: 'id_5'
        widget: 'string'
      - label: 'YouTube ID #6'
        name: 'id_6'
        widget: 'string'
  - name: sliding_images
    label: Sliding Images
    folder: public/content/pages
    create: true
    fields:
      - label: 'Images'
        name: 'images'
        widget: 'list'
        fields:
          - label: 'Image'
            name: 'image'
            widget: 'image'
          - label: 'Descripive Text'
            name: 'alt_text'
            widget: 'string'
site_config:
  name: site-config
  file: data/site-config.json
  label: Site Configuration
  create: true
  delete: true
  editor:
    preview: true
  fields:
    - name: title
      label: Site Title
      widget: string
    - name: metaDescription
      label: Meta Description
      widget: text
